export const topics = [
  "World Capitals",
  "Famous Landmarks",
  "Inventions and Inventors",
  "Flags of the World",
  "Nobel Prize Winners",
  "Basic Mathematics",
  "Human Body & Anatomy",
  "Physics Fundamentals",
  "Vocabulary & Grammar",
  "Famous Books & Authors",
  "Movie Trivia",
  "TV Shows & Sitcoms",
  "Celebrity Guessing",
  "Oscars & Awards",
  "Animated Films & Characters",
  "Classic Video Games",
  "Esports & Streamers",
  "Game Soundtracks",
  "Gaming Consoles",
  "Game Logos & Characters",
  "Music Genres",
  "Guess the Song from Lyrics",
  "Famous Musicians/Bands",
  "Instruments Around the World",
  "Grammy Winners",
  "Countries by Shape",
  "Mountains & Rivers",
  "Natural Wonders",
  "Time Zones & Continents",
  "Bordering Countries",
  "Ancient Civilizations",
  "World Wars",
  "Historical Leaders",
  "Timeline Challenge",
  "Famous Revolutions",
  "Riddles",
  "Pattern Recognition",
  "Lateral Thinking",
  "Math Puzzles",
  "Which One Doesn’t Belong?",
  "Periodic Table",
  "Space & Astronomy",
  "Animals & Habitats",
  "Weather & Climate",
  "Scientific Discoveries",
  "Tech Founders",
  "Internet Acronyms",
  "Programming Languages",
  "Famous Apps & Tools",
  "Cybersecurity Basics",
  "Olympic Games",
  "Football World Cups",
  "Tennis Grand Slams",
  "NBA/NFL/Cricket Trivia",
  "Famous Athletes",
  "Indian Festivals",
  "Indian History",
  "Indian Cinema",
  "Indian Cuisine",
  "Indian Constitution & Politics",
  "World Art Movements",
  "Classical Paintings",
  "Architecture Styles",
  "World Mythologies",
  "Dance & Theater",
  "Famous Companies",
  "Stock Market Basics",
  "Cryptocurrency",
  "Business Tycoons",
  "Brand Logos",
  "Memes & Internet Trends",
  "Fashion & Style",
  "Famous Quotes",
  "Food & Drinks",
  "Would You Rather? Style Trivia",
];

export const getRandomTopic = () => {
  return topics[Math.floor(Math.random() * topics.length)];
};
